//Initial state of the app
import { AppState } from './types'

export const initialState: AppState = {
  'colors.primary': {
    name: 'colors.primary',
    computedValue: '#000000',
    description: 'Primary font color',
    refs: [],
    referencedBy: [],
    category: 'General Colors',
    rawValue: '#000000',
    type: 'color',
  },
  'colors.primaryBackground': {
    name: 'colors.primaryBackground',
    computedValue: '#ffffff',
    description: 'Primary background color',
    refs: [],
    referencedBy: [],
    category: 'General Colors',
    rawValue: '#ffffff',
    type: 'color',
  },
  'colors.secondary': {
    name: 'colors.secondary',
    computedValue: '#ffffff',
    description: 'Secondary font color',
    refs: [],
    referencedBy: [],
    category: 'General Colors',
    rawValue: '#ffffff',
    type: 'color',
  },
  'colors.secondaryBackground': {
    name: 'colors.secondaryBackground',
    computedValue: '#4a86e8',
    description: 'Secondary background color',
    refs: [],
    referencedBy: [],
    category: 'General Colors',
    rawValue: '#4a86e8',
    type: 'color',
  },
  'colors.highlight1': {
    name: 'colors.highlight1',
    computedValue: '#4a86e8',
    description: 'Highlight on primary background',
    refs: [],
    referencedBy: [],
    category: 'General Colors',
    rawValue: '#4a86e8',
    type: 'color',
  },
  'colors.highlight2': {
    name: 'colors.highlight2',
    computedValue: '#ffab40',
    description: 'Highlight on secondary background',
    refs: [],
    referencedBy: [],
    category: 'General Colors',
    rawValue: '#ffab40',
    type: 'color',
  },
  'sizes.text': {
    name: 'sizes.text',
    computedValue: '1.1',
    description: 'Default text size',
    refs: [],
    referencedBy: [],
    category: 'Global Sizes',
    rawValue: '1.1',
    type: 'em',
  },
  'sizes.h1': {
    name: 'sizes.h1',
    computedValue: '1.4',
    description: 'Header1 text size',
    refs: [],
    referencedBy: [],
    category: 'Global Sizes',
    rawValue: '1.4',
    type: 'em',
  },
  'sizes.h2': {
    name: 'sizes.h2',
    computedValue: '1.2',
    description: 'Header2 text size',
    refs: [],
    referencedBy: [],
    category: 'Global Sizes',
    rawValue: '1.2',
    type: 'em',
  },
  'sizes.borderWidth': {
    name: 'sizes.borderWidth',
    computedValue: '1',
    description: 'Default border width',
    refs: [],
    referencedBy: [],
    category: 'Global Sizes',
    rawValue: '1',
    type: 'px',
  },
  'textfield.textSize': {
    name: 'textfield.textSize',
    computedValue: '1.1',
    description: 'Text size',
    refs: [],
    referencedBy: [],
    category: 'Text Field',
    rawValue: '1.1',
    type: 'em',
  },
  'textfield.color': {
    name: 'textfield.color',
    computedValue: '#000000',
    description: 'Font color',
    refs: [],
    referencedBy: [],
    category: 'Text Field',
    rawValue: '#000000',
    type: 'color',
  },
  /*    'textfield.border' : {
            name: 'textfield.border',
            computedValue : '1px solid #000000',
            description : 'Border',
            refs :[],
            referencedBy :[],
            category : 'Text Field',
            rawValue : '1px solid #000000',
            type : 'color'
        },*/
  'textfield.background': {
    name: 'textfield.background',
    computedValue: '#ffffff',
    description: 'Background',
    refs: [],
    referencedBy: [],
    category: 'Text Field',
    rawValue: '#ffffff',
    type: 'color',
  },
  'buttons.color': {
    name: 'buttons.color',
    computedValue: '#000000',
    description: 'Font color',
    refs: [],
    referencedBy: [],
    category: 'Buttons',
    rawValue: '#000000',
    type: 'color',
  },
  'buttons.background': {
    name: 'buttons.background',
    computedValue: '#4a86e8',
    description: 'Background',
    refs: [],
    referencedBy: [],
    category: 'Buttons',
    rawValue: '#4a86e8',
    type: 'color',
  },
}
